[reset_default_unattended]
name = "Reset the 50unattended-upgrades config file and restore a default one."
command = "/bin/bash scripts/actions/reset_default_config \"50unattended-upgrades\""
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the unattended-upgrades config file 50unattended-upgrades."

[reset_default_periodic]
name = "Reset the 02periodic apt config file and restore a default one."
command = "/bin/bash scripts/actions/reset_default_config \"02periodic\""
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the config file 02periodic."


[reset_default_app]
name = "Reset the app with a default configuration."
command = "/bin/bash scripts/actions/reset_default_app"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the app to its default configuration to try to fix potential issues.<br>This action won't remove any data added to the app.<br>However, if you have modified any configuration, it will be overwritten."
