#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP UNATTENDED-UPGRADES CONFIG
#=================================================

ynh_backup "$apticron_config"

ynh_backup "$apticron_cron"

ynh_backup "/etc/apt/apt.conf.d/51unattended-upgrades-override"

ynh_backup "/etc/apt/apt.conf.d/02periodic"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
