#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# BACKUP UNATTENDED-UPGRADES CONFIG
#=================================================

ynh_backup --src_path="/etc/apt/apt.conf.d/50unattended-upgrades"
# Backup also the backup of the config file
ynh_backup --src_path="/etc/apt/50unattended-upgrades.backup"

#=================================================
# BACKUP APT PERIODIC
#=================================================

ynh_backup --src_path="/etc/apt/apt.conf.d/02periodic"

#=================================================
# BACKUP APTICRON CONFIG
#=================================================

ynh_backup --src_path="/etc/apticron/apticron.conf"

#=================================================
# BACKUP THE CRON FILE
#=================================================

ynh_backup --src_path="/etc/cron.d/apticron"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
