#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# BACKUP UNATTENDED-UPGRADES CONFIG
#=================================================

ynh_backup --src_path="$apticron_config"
ynh_backup --src_path="$apticron_config_backup"

ynh_backup --src_path="$apticron_cron"
ynh_backup --src_path="$apticron_cron_backup"

ynh_backup --src_path="$unattended_upgrades_config"
ynh_backup --src_path="$unattended_upgrades_config_backup"

ynh_backup --src_path="/etc/apt/apt.conf.d/02periodic"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
