#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE VARIABLES FOR POST_INSTALL.md
#=================================================

# Get main domain and buid the url of the admin panel of the app.
admin_panel="https://$(grep portal_domain /etc/ssowat/conf.json | cut -d'"' -f4)/yunohost/admin/#/apps/$app"
ynh_app_setting_set --app="$app" --key=admin_panel --value="$admin_panel"

# ynh_app_setting_set --app=$app --key=overwrite_periodic --value=1
# ynh_app_setting_set --app=$app --key=admin_mail_html --value=1

#=================================================
# CONFIGURE APTICRON
#=================================================
ynh_script_progression --message="Configuring Apticron..."

_apticron_set_config

#=================================================
# CONFIGURE UNATTENDED-UPGRADES
#=================================================
ynh_script_progression --message="Configuring Unattended-Upgrades..."

_unattended_upgrades_set_config

#=================================================
# CONFIGURE APT PERIODIC FOR UNATTENDED
#=================================================
ynh_script_progression --message="Configure APT Periodic for Unattended" --weight=2

ynh_add_config --template="../conf/02periodic" --destination="/etc/apt/apt.conf.d/02periodic"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
