#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE UNATTENDED-UPGRADES CONFIG
#=================================================

ynh_restore_file --origin_path="$apticron_config"

ynh_restore_file --origin_path="$apticron_cron"

ynh_restore_file --origin_path="$unattended_upgrades_config"

ynh_restore_file --origin_path="/etc/apt/apt.conf.d/02periodic"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
