#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers
source _sed

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

unattended_verbosity=$(ynh_app_setting_get $app unattended_verbosity)

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# It's impossible to make a backup here, because the backup name is going to have 32 characters. Which is not allowed...

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies apticron unattended-upgrades apt-listchanges

#=================================================
# SPECIFIC UPGRADE
#=================================================
# UPGRADE APTICRON
#=================================================

# Nothing to do here...

#=================================================
# UPGRADE UNATTENDED-UPGRADES
#=================================================

# Nothing to do here...

#=================================================
# UPGRADE APT PERIODIC FOR UNATTENDED
#=================================================

ynh_backup_if_checksum_is_different "/etc/apt/apt.conf.d/02periodic"

cp "../conf/02periodic" "/etc/apt/apt.conf.d/02periodic"
ynh_replace_string "__VERBOSITY__" "$unattended_verbosity" "/etc/apt/apt.conf.d/02periodic"
# This config file is used by /etc/cron.daily/apt

ynh_store_file_checksum "/etc/apt/apt.conf.d/02periodic"

#=================================================
# UPGRADE APTICRON CRON FILE
#=================================================

# Nothing to do here...
