#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Load common variables for all scripts.
source scripts/_variables

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=$YNH_APP_INSTANCE_NAME

unattended_verbosity=$(ynh_app_setting_get --app=$app --key=unattended_verbosity)
upgrade_level="$(ynh_app_setting_get --app=$app --key=upgrade_level)"
ynh_update=$(ynh_app_setting_get --app=$app --key=ynh_update)
unattended_mail="$(ynh_app_setting_get --app=$app --key=unattended_mail)"
previous_apticron=$(ynh_app_setting_get --app=$app --key=previous_apticron)
after_apticron=$(ynh_app_setting_get --app=$app --key=after_apticron)

#=================================================
# SPECIFIC ACTION
#=================================================
# RESET APTICRON CONFIGURATION
#=================================================
ynh_script_progression --message="Resetting Apticron..."

apticron_config="/etc/apticron/apticron.conf"
cp "conf/apticron.conf.backup" "$apticron_config"
ynh_replace_string --match_string="# CUSTOM_SUBJECT=.*" \
    --replace_string="&\nCUSTOM_SUBJECT=\'[apticron] \$SYSTEM: \$NUM_PACKAGES package update(s)\'" --target_file="$apticron_config"
ynh_replace_string --match_string="# CUSTOM_NO_UPDATES_SUBJECT=.*" \
    --replace_string="&\nCUSTOM_NO_UPDATES_SUBJECT=\'[apticron] \$SYSTEM: Up to date \\\\o/\'" --target_file="$apticron_config"

#=================================================
# RESET UNATTENDED-UPGRADES CONFIGURATION
#=================================================
ynh_script_progression --message="Resetting unattended-upgrades..."

yunohost app action run $app reset_default_unattended

#=================================================
# RESET APT PERIODIC CONFIGURATION
#=================================================
ynh_script_progression --message="Resetting apt periodic..."

yunohost app action run $app reset_default_periodic

#=================================================
# RESET APTICRON CRON FILE
#=================================================
ynh_script_progression --message="Resetting apticron cron file..."

apticron_cron="/etc/cron.d/apticron"
cp "conf/apticron.crond.backup" "$apticron_cron"

# Copy and comment the current cron
ynh_replace_string --match_string="^.* root if.*" --replace_string="#&\n&" --target_file="$apticron_cron"
# Modify the time to set at 20:00 every day
ynh_replace_string --match_string="^[[:digit:]].*\( root if.*\)" --replace_string="0 20 * * *\1" --target_file="$apticron_cron"
# Copy the new cron and set the time to 2:00 every night
ynh_replace_string --match_string="^0 20\(.*\)" --replace_string="&\n0 2\1" --target_file="$apticron_cron"

if [ $previous_apticron -eq 0 ]
then
    # Comment the first cron
    ynh_replace_string --match_string="^0 20 .*" --replace_string="#&" --target_file="$apticron_cron"
fi

if [ $after_apticron -eq 0 ]
then
    # Comment the second cron
    ynh_replace_string --match_string="^0 2 .*" --replace_string="#&" --target_file="$apticron_cron"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
