#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=2

app=$YNH_APP_INSTANCE_NAME

upgrade_level="$(ynh_app_setting_get --app=$app --key=upgrade_level)"
ynh_update=$(ynh_app_setting_get --app=$app --key=ynh_update)
unattended_mail="$(ynh_app_setting_get --app=$app --key=unattended_mail)"
unattended_verbosity=$(ynh_app_setting_get --app=$app --key=unattended_verbosity)

#=================================================
# SORT OUT THE CONFIG FILE TO HANDLE
#=================================================

file="$1"

if [ "$file" = "50unattended-upgrades" ]; then
    config_file="/etc/apt/apt.conf.d/50unattended-upgrades"
elif [ "$file" = "02periodic" ]; then
    config_file="/etc/apt/apt.conf.d/02periodic"
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# RESET THE CONFIG FILE
#=================================================
ynh_script_progression --message="Resetting the config file $config_file..." --weight=9

# Verify the checksum and backup the file if it's different
ynh_backup_if_checksum_is_different --file="$config_file"

# Reset the config /etc/apt/apt.conf.d/50unattended-upgrades
if [ "$file" = "50unattended-upgrades" ]
then
    # Get the default file and overwrite the current config
    cp /etc/apt/50unattended-upgrades.backup "$config_file"

    # Recreate the default config
    # Allow security update
    ynh_replace_string --match_string="//\(.*\"o=Debian,n=$(ynh_get_debian_release),l=Debian-Security\";\)" --replace_string="\1" --target_file="$config_file"
    # Allow other updates
    if [ "$upgrade_level" = "Security and updates" ]
    then
        ynh_replace_string --match_string="//\(.*\"o=Debian,n=$(ynh_get_debian_release)\";\)" --replace_string="\1" --target_file="$config_file"
        ynh_replace_string --match_string="//\(.*\"o=Debian,n=$(ynh_get_debian_release)-updates\";\)" --replace_string="\1" --target_file="$config_file"
    fi

    # Add YunoHost upgrade source
    if [ $ynh_update -eq 1 ]
    then
        ynh_replace_string --match_string="origin=Debian,codename=\$(ynh_get_debian_release),label=Debian-Security\";" \
            --replace_string="&\n\n        //YunoHost upgrade\n        \"o=YunoHost,n=$(ynh_get_debian_release)\";" --target_file="$config_file"
    fi

    # Allow MinimalSteps upgrading to reduce risk in case of reboot
    ynh_replace_string --match_string="//\(Unattended-Upgrade::MinimalSteps\).*" --replace_string="\1 \"true\";" --target_file="$config_file"

    # Configure Unattended Upgrades mailing
    if [ "$unattended_mail" = "If an upgrade has been done" ]
    then
        # Allow mail to root
        ynh_replace_string --match_string="//\(Unattended-Upgrade::Mail \)" --replace_string="\1" --target_file="$config_file"

        # Send mail even if there's no errors
        ynh_replace_string --match_string="//\(Unattended-Upgrade::MailOnlyOnError \).*" --replace_string="\1\"false\";" --target_file="$config_file"

    elif [ "$unattended_mail" = "Only if there was an error" ]
    then
        # Allow mail to root
        ynh_replace_string --match_string="//\(Unattended-Upgrade::Mail \)" --replace_string="\1" --target_file="$config_file"

        # Send mail only if there's an error
        ynh_replace_string --match_string="//\(Unattended-Upgrade::MailOnlyOnError \).*" --replace_string="\1\"true\";" --target_file="$config_file"

    else	# "Never"
        # Comment "Unattended-Upgrade::Mail" if it isn't already commented
        ynh_replace_string --match_string="^\(Unattended-Upgrade::Mail \)" --replace_string="//\1" --target_file="$config_file"
    fi
fi

# Reset the config /etc/apt/apt.conf.d/02periodic
if [ "$file" = "02periodic" ]
then
    # Get the default file and overwrite the current config
    ynh_add_config --template="../conf/02periodic" --destination="/etc/apt/apt.conf.d/02periodic"
fi

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum --file="$config_file"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
